name: My first pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: uptime
         run: mproc
       - name: Number processor
         run: date          

  test:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo hello 